# NOTE https://www.gnupg.org/documentation/manuals/gnupg/GPG-Options.html

default-key 1CE4793E824CC27BB6CB54DB2BCBB04EFBCBE84A

auto-key-locate local,pka,dane

keyserver-options auto-key-retrieve no-include-revoked

# list-options show-photos

no-escape-from-lines

no-greeting

keyid-format short
# with-subkey-fingerprint
# with-keygrip
