return {
    {
        "nvim-treesitter/nvim-treesitter",
        enbled = false,
        lazy = false,
        build = ":TSUpdate",
        config = function ()
            require( "nvim-treesitter" ).setup( {
                install_dir = vim.fn.stdpath( "data" ) .. "/site"
            } );

            require( "nvim-treesitter" ).install( {
                "awk",
                "bash",
                "c",
                "cmake",
                "comment",
                "cpp",
                "css",
                "csv",
                "diff",
                "dockerfile",
                "editorconfig",
                "embedded_template",
                "forth",
                "git_config",
                "gitattributes",
                "gitignore",
                "gpg",
                "graphql",
                "html",
                "ini",
                "javascript",
                "jsdoc",
                "json",
                "json5",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "nginx",
                "pem",
                "perl",
                "php",
                "po",
                "pod",
                "powershell",
                "printf",
                "python",
                "query",
                "readline",
                "regex",
                "scss",
                "sql",
                "ssh_config",
                "toml",
                "tsv",
                "typescript",
                "vim",
                "vimdoc",
                "vue",
                "xml",
                "yaml"
            } );
        end,
    },
}
