#!/bin/sh

set -e

if [ -x "$(command -v softvisio-cli)" ]; then
    softvisio-cli git commit-msg $1
elif [ -x "$(command -v npx)" ] && [ -f node_modules/.bin/softvisio-cli ]; then
    npx softvisio-cli git commit-msg $1
fi
