#!/bin/sh

set -e

if [ -x "$(command -v softvisio-cli)" ]; then
    softvisio-cli git pre-commit
elif [ -x "$(command -v npx)" ] && [ -f node_modules/.bin/softvisio-cli ]; then
    npx softvisio-cli git pre-commit
fi
