#!/usr/bin/env -S bash

set -Eeuo pipefail

if [[ -x node_modules/.bin/zcli ]]; then
    node_modules/.bin/zcli git pre-commit-hook
elif [[ -x "$(command -v zcli)" ]]; then
    zcli git pre-commit-hook
fi
