function:
  trigger: CREATE FUNCTION
  body: |-
    CREATE FUNCTION $1 ( p_ text ) RETURNS text AS \$\$
    DECLARE
        v_ text;
    BEGIN
        RETURN v_;
    END;
    \$\$ LANGUAGE plpgsql;
trigger:
  trigger: CREATE TRIGGER
  body: |-
    CREATE FUNCTION $1_after_update_or_delete_trigger () RETURNS TRIGGER AS \$\$
    DECLARE
        v_ text;
    BEGIN
        RETURN NULL;
    END;
    \$\$ LANGUAGE plpgsql;

    CREATE TRIGGER $2_after_update_or_delete AFTER UPDATE OR DELETE ON $3_table FOR EACH ROW EXECUTE FUNCTION $4_after_update_or_delete_trigger();
